### ISSUE TITLE
about a bug

### ISSUE THREAD

**Issue by JiangZhenW** [hrzhou2/seedformer#1]
your work is wonderful, but i find a small mistake, following
https://github.com/hrzhou2/seedformer/blob/10a3a33d9eeac990fff889194912662748a4b8f7/codes/manager.py#L262
the error is keyword can't be an expression

if the right code is '''self.test_record(message. show_info==False)? but when i edit it,the traing stage seems can not work

**Comment by hrzhou2** [comment]
Fixed now. Thanks.
